name: lint and test

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python/poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: true
      - name: Black
        run: poetry run black . --check
      - name: Flake8
        run: poetry run flake8 
      - name: run coverage
        run: poetry run pytest --cov-report xml --cov=chaptify tests/
        env:
          CLIENT_ID: test
          CLIENT_SECRET: test
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          flags: unittests
